# Site settings
title: "Jonathan Loera"
description: "Jonathan Loera's resume created with Jekyll and hosted on GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Jonathan Loera"
resume_title:                   "Summary"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jonathanloera20@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(651) 278-0214"
resume_contact_address:         ""

resume_header_contact_info:     "jonathanloera20@gmail.com • (651) 278-0214"
display_header_contact_info:    "true"

resume_header_intro: "<p>I'm a fifth-year student at University of Wisconsin-Stout studying towards a Bachelor's in Criminal Justice and Rehabilitation. I'm studying Criminal Justice because I'm interested in this field and have ambitions to further my growth towards working in a federal agency. Outside of school I was a captain in the Track and Field team for Stout, and volunteer helping the local community of Menomonie.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          false
resume_section_recognition:     true
resume_section_links:           false
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/jglovier/resume-template"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  #resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  #resume_pdf_url:               "https://jonathanloera.github.io/images/christian-loera-resume.pdf"
  #resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
